In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]
arr = np.array(lst)

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr.shape

(4,)

In [9]:
arr.reshape(2,2 )

array([[1, 2],
       [3, 4]])

In [7]:
arr.shape

(4,)

###Array Indexing

In [10]:
arr[0]

1

In [11]:
array = np.arange(0,50)

In [12]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
array.shape

(50,)

In [15]:
array.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [16]:
array[0] + array[3]

3

In [19]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10] , [11,12,13,14,15]])


In [20]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

###Array Slicing

In [24]:
arr2[1:3 , 2:4]

array([[ 8,  9],
       [13, 14]])

In [28]:
arr2[1:2 , 1:4]

array([[7, 8, 9]])

In [29]:
arr2[1,1:4]

array([7, 8, 9])

In [32]:
arr2[1 , 1:2]

array([7])